listt=[]
print("enter saven fruit names in your list")
f1=input("enter the fruit name")
listt.append(f1)
f2=input("enter the fruit name")
listt.append(f2)
f3=input("enter the fruit name")
listt.append(f3)
f4=input("enter the fruit name")
listt.append(f4)
f5=input("enter the fruit name")
listt.append(f5)
f6=input("enter the fruit name")
listt.append(f6)
print(listt)
